spring.application.name=worker

spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

minio.bucket=${MINIO_BUCKET:}
minio.endpoint=${MINIO_ENDPOINT:}
minio.region=${MINIO_REGION:eu-central-1}
minio.access-key=${MINIO_ACCESS_KEY:}
minio.secret-key=${MINIO_SECRET_KEY:}

app.minio.enabled=${APP_MINIO_ENABLED:true}
app.kafka.enabled=${APP_KAFKA_ENABLED:true}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
