services:
  api:
    image: file-storage-api:latest
    env_file:
      - path: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
      min-io:
        condition: service_started
  worker:
    image: file-storage-worker:latest
    env_file:
      - path: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: worker
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
      min-io:
        condition: service_started
  broker:
    image: apache/kafka:4.1.1
    container_name: broker
    environment:
      KAFKA_NODE_ID:  1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - type: volume
        source: kafka_data
        target: /var/lib/kafka/data
    ports:
      - "9092:9092"
  min-io:
    image: quay.io/minio/aistor/minio:latest
    environment:
      # TODO выпустить нормальные ключи
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ${MINIO_LICENSE_FILE}
        target: /minio.license
        read_only: true

      - type: volume
        source: minio_data
        target: /mnt/data

      - type: volume
        source: minio_certs
        target: /etc/minio/certs
    entrypoint: minio server /mnt/data --license /minio.license
    ports:
      - "9000:9000"
      - "9001:9001"
  db:
    image: postgres:18.2
    ports:
      - "9876:5432"
    shm_size: 512mb
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER -h 127.0.0.1 || exit 1" ]
      interval: 1m
      timeout: 3s
      retries: 1
      start_period: 30s
      start_interval: 3s
volumes:
  minio_data:
  minio_certs:
  kafka_data:
  pg_data:

networks:
  minio_net: