spring.application.name=api
spring.kafka.producer.batch-size=100

spring.config.import=optional:application-datasource.properties,optional:application-minio.properties,optional:application-token.properties

logging.level.org.springframework=INFO
logging.level.io.minio=DEBUG
logging.level.dev.dentron=DEBUG

management.endpoints.web.exposure.include=health,info,beans,mappings,env
