spring.application.name=api
spring.kafka.producer.batch-size=100

spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

minio.bucket=${MINIO_BUCKET:}
minio.endpoint=${MINIO_ENDPOINT:}
minio.region=${MINIO_REGION:eu-central-1}
minio.access-key=${MINIO_ACCESS_KEY:}
minio.secret-key=${MINIO_SECRET_KEY:}

logging.level.org.springframework=INFO
logging.level.io.minio=DEBUG
logging.level.dev.dentron=DEBUG
logging.level.org.flywaydb=DEBUG

management.endpoints.web.exposure.include=health,info,beans,mappings,env

app.minio.enabled=${APP_MINIO_ENABLED:true}
app.kafka.enabled=${APP_KAFKA_ENABLED:true}
jwt.public-key=${API_JWT_PUBLIC_KEY:}
download.token.secret=${API_DOWNLOAD_TOKEN_SECRET:change_me}

app.cors.actuator.enabled=true
app.cors.actuator.path-pattern=/actuator/**
app.cors.actuator.allowed-origins=*
app.cors.actuator.allowed-methods=GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.actuator.allowed-headers=*
app.cors.actuator.exposed-headers=
app.cors.actuator.max-age-seconds=3600
app.cors.actuator.allow-credentials=false

app.cors.internal.enabled=true
app.cors.internal.path-pattern=/**
app.cors.internal.allowed-origins=*
app.cors.internal.allowed-methods=GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.internal.allowed-headers=*
app.cors.internal.exposed-headers=
app.cors.internal.max-age-seconds=3600
app.cors.internal.allow-credentials=false

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
