CREATE TABLE download_token
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash          VARCHAR(255)                            NOT NULL,
    file_id             UUID                                    NOT NULL,
    issued_by_service   VARCHAR(255)                            NOT NULL,
    audience_service    VARCHAR(255)                            NOT NULL,
    expires_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    redeemed_at         TIMESTAMP WITH TIME ZONE,
    redeemed_by_service VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    revoked_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_download_token PRIMARY KEY (id)
);

CREATE TABLE file_object
(
    id            UUID                     NOT NULL,
    bucket        VARCHAR(255)             NOT NULL,
    owner         VARCHAR(255)             NOT NULL,
    object_key    VARCHAR(255)             NOT NULL,
    original_name VARCHAR(255),
    size          BIGINT,
    sha256        VARCHAR(255),
    etag          VARCHAR(255),
    content_type  VARCHAR(255),
    status        VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_file_object PRIMARY KEY (id)
);

CREATE TABLE outbox_event
(
    id             UUID                     NOT NULL,
    event_type     VARCHAR(255)             NOT NULL,
    aggregate_type VARCHAR(255)             NOT NULL,
    aggregate_id   VARCHAR(255)             NOT NULL,
    payload        JSONB                    NOT NULL,
    status         VARCHAR(255)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_outbox_event PRIMARY KEY (id)
);

CREATE TABLE upload_session
(
    id                    UUID                     NOT NULL,
    multipart_upload_id   VARCHAR(255)             NOT NULL,
    file_id               UUID                     NOT NULL,
    expires_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    expected_size         BIGINT,
    expected_content_type VARCHAR(255),
    status                VARCHAR(255)             NOT NULL,
    CONSTRAINT pk_upload_session PRIMARY KEY (id)
);

ALTER TABLE download_token
    ADD CONSTRAINT uc_download_token_file UNIQUE (file_id);

ALTER TABLE download_token
    ADD CONSTRAINT uc_download_token_token_hash UNIQUE (token_hash);

ALTER TABLE download_token
    ADD CONSTRAINT FK_DOWNLOAD_TOKEN_ON_FILE FOREIGN KEY (file_id) REFERENCES file_object (id);
